# Generated by Django 4.2.7 on 2023-12-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datastamp', models.DateTimeField(verbose_name='Дата')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Температура')),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Влажность')),
                ('coolState', models.BooleanField(verbose_name='Вентилятор')),
                ('releState', models.BooleanField(verbose_name='Освещение')),
            ],
        ),
    ]
