# Generated by Django 4.2.7 on 2023-12-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdhome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbtelemetry',
            name='humidity',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='Влажность'),
        ),
        migrations.AlterField(
            model_name='dbtelemetry',
            name='temperatura',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Температура'),
        ),
    ]
