# Generated by Django 4.2.7 on 2024-02-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdhome', '0003_alter_dbtelemetry_datastamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbtelemetry',
            name='datastamp',
            field=models.DateTimeField(db_index=True, unique=True, verbose_name='Дата'),
        ),
    ]
