# Generated by Django 4.2.7 on 2024-05-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdhome', '0004_alter_dbtelemetry_datastamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbtelemetry',
            name='rainState',
            field=models.BooleanField(default=False, verbose_name='Полив'),
            preserve_default=False,
        ),
    ]
